### ISSUE TITLE
安装不成功

### ISSUE THREAD

**Issue by myy520** [VSNeoVim/VSNeoVim#11]
处理 /Users/rising/.config/nvim/init.lua 时发生错误:
E5113: Error while calling lua chunk: /Users/rising/.config/nvim/lua/vsn/extension-loader.lua:27: attempt to call field 'init' (a nil value)
stack traceback:
        /Users/rising/.config/nvim/lua/vsn/extension-loader.lua:27: in function 'init'
        /Users/rising/.config/nvim/init.lua:10: in main chunk
请按 ENTER 或其它命令继续

**Comment by smsameet** [comment]
if you run this ?
bash <(curl -s https://raw.githubusercontent.com/vsneovim/vsneovim/master/utils/installer/install.sh)
