### ISSUE TITLE
Consider change alpha header text?

### ISSUE THREAD

**Issue by Pandademic** [VSNeoVim/VSNeoVim#4]
Maybe change it to:

[Link](https://patorjk.com/software/taag/#p=display&v=0&f=Electronic&t=VS%20NEOVIM)

**Comment by smsameet** [comment]
This is a good issue, but the header you have chosen is not very interesting

**Comment by Pandademic** [comment]
How about:

db    db .d8888.      d8b   db d88888b  .d88b.  db    db d888888b .88b  d88. 
88    88 88'  YP      888o  88 88'     .8P  Y8. 88    88   `88'   88'YbdP`88 
Y8    8P `8bo.        88V8o 88 88ooooo 88    88 Y8    8P    88    88  88  88 
`8b  d8'   `Y8b.      88 V8o88 88~~~~~ 88    88 `8b  d8'    88    88  88  88 
 `8bd8'  db   8D      88  V888 88.     `8b  d8'  `8bd8'    .88.   88  88  88 
   YP    `8888Y'      VP   V8P Y88888P  `Y88P'     YP    Y888888P YP  YP  YP

**Comment by smsameet** [comment]
great. but ????

 which is: (link)[https://patorjk.com/software/taag/#p=display&v=0&f=Basic&t=VS%20NEOVIM]

**Comment by Pandademic** [comment]
[Go to this URL](https://patorjk.com/software/taag/#p=display&v=0&f=Basic&t=VS%20NEOVIM)

**Comment by smsameet** [comment]
thanks . pushed

**Comment by Pandademic** [comment]
np
