### ISSUE TITLE
Deprecated error

### ISSUE THREAD

**Issue by RZHSSNZDH** [VSNeoVim/VSNeoVim#8]
Always error below is shown under the status bar:
`vim.lsp.diagnostic.get_all is deprecated. See :h deprecated`

![نماگرفت از 2022-02-04 15-49-12](https://user-images.githubusercontent.com/69734726/152530695-becb5a67-e2d5-4e69-9e87-00f2f038a55a.png)

**Comment by smsameet** [comment]
npm version ?

**Comment by RZHSSNZDH** [comment]
> npm and neovim version ?

npm: 8.4.0
nvim: 0.6.1

**Comment by smsameet** [comment]
I also had this problem, but this bug has already been fixed! Is there a problem with the language server you have installed? Is the compilation done correctly?

**Comment by RZHSSNZDH** [comment]
> I also had this problem, but this bug has already been fixed! Is there a problem with the language server you have installed? Is the compilation done correctly?

I do not have installed a LSP

**Comment by smsameet** [comment]
for programming languages ...
`` :LspInstall <lang>``

However, I checked again that , you can pull for the configurations again
``bash
git pull
``

**Comment by RZHSSNZDH** [comment]
> for programming languages ... ` :LspInstall <lang>`

I know that. I mean the problem is not because of an LSP.

> However, I checked again that , you can pull for the configurations again `git pull`

The problem still exists. I searched for `vim.lsp.diagnostic.get_all` in the codes but can't find. If you find it, you can replace it with `vim.lsp.diagnostic.get` to resolve the problem.

**Comment by RZHSSNZDH** [comment]
I found the problem! You should replace all `vim.lsp.diagnostic.get` with `vim.diagnostic.get` in `.local/share/nvim/lsp_servers`.

**Comment by smsameet** [comment]
See this problem solved! And the path that had to be replaced was the same LSP and Handlers configurations that were changed.

So is the problem solved?

**Comment by RZHSSNZDH** [comment]
> See this problem solved! And the path that had to be replaced was the same LSP and Handlers configurations that were changed.
> 
> ‍‍‍‍`~/.config/nvim/visualstudioneovim/config/lsp/handlers.lua`
> 
> So is the problem solved?

Now I do not have the problem! Tnx

**Comment by smsameet** [comment]
:) A word of advice to you: Install Nerd Fonts for your terminal. I use the CaskaydiaCove font myself.

**Comment by RZHSSNZDH** [comment]
> :) A word of advice to you: Install Nerd Fonts for your terminal. I use the `CaskaydiaCove` font my self.

Thanks, but is there a problem in my nvim? Symbols are shown well as I expect.

**Comment by smsameet** [comment]
No ! this was just a suggestion :)
